using Spire.Xls;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace ExcelToHTML
{
    class Program
    {
        static void Main(string[] args)
        {
            string path = @"ОСВ для задания.xls";
            string outPath = @"ОСВ.html";
            int sheetNumber = 0;

            try
            {

                if (true)//with template
                {
                    string htmlText = GetHtmlFromXls(path, sheetNumber);

                    //Save in file
                    using (TextWriter sw = new StreamWriter(outPath, false, System.Text.Encoding.Default))
                    {
                        sw.WriteLine(RemoveWarn(htmlText));
                    }
                }

                if (false) //OR without load
                {
                    Workbook workbook = new Workbook();
                    workbook.LoadFromFile(path);
                    Worksheet sheet = workbook.Worksheets[sheetNumber];
                    sheet.SaveToHtml(outPath);
                }


                //Preview HTML
                System.Diagnostics.Process.Start(outPath);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            Console.ReadKey();
        }

        // 1. Read the xlsx file
        // 2. Convert to html format
        static string GetHtmlFromXls(string path, int sheetNumber)
        {
            FileStream fs = File.OpenRead(path);

            // FileStream to MemoryStream, to overcome the FileAccess
            byte[] bytes = new byte[fs.Length];
            fs.Read(bytes, 0, (int)fs.Length);
            MemoryStream ms = new MemoryStream(bytes);

            //load Excel file
            Workbook workbook = new Workbook();
            workbook.LoadFromStream(ms);

            //convert Excel to HTML
            Worksheet sheet = workbook.Worksheets[sheetNumber];
            MemoryStream htmlStream = new MemoryStream();
            sheet.SaveToHtml(htmlStream);
            byte[] byteArray = htmlStream.ToArray();
            return Encoding.UTF8.GetString(byteArray);
        }

        // Remove the warning generated by Spire.XLS
        static string RemoveWarn(string sourcestring)
        {
            String matchpattern = @"\s?<h2[^<]*>[^<]+</h2>\s?";
            String replacementpattern = String.Empty;
            return Regex.Replace(sourcestring, matchpattern, replacementpattern).Substring(1);
        }
    }
}
